name: Deploy in Production to EC2 Production

on:
  pull_request:
    branches:
      - main  
jobs:
  deploy-Front:
    runs-on: ubuntu-latest

    steps:
    
    - name: Set up SSH key for EC2
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEYP }}

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker images for frontend
      run: |
        docker build -t chamorrito/my-react-app ./FrontEnd

    - name: Push images to Docker Hub
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push chamorrito/my-react-app

    - name: Deploy services to EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: 98.87.70.243
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEYP }}
        script: |
          docker stop my-react-app || true
          docker rm my-react-app || true

          docker pull chamorrito/my-react-app

          docker run -d --name my-react-app -p 80:80 --restart unless-stopped chamorrito/my-react-app

  deploy-auth:
    name: Deploy Auth Services
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEYP }}

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Auth images
        run: |
          docker build -t chamorrito/login-service ./BackEnd/Authentication-Domain/Login
          docker build -t chamorrito/register-service ./BackEnd/Authentication-Domain/Register

      - name: Push Auth images
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push chamorrito/login-service
          docker push chamorrito/register-service

      - name: Deploy Auth services to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 54.175.228.248
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEYP }}
          script: |
            docker stop login-service || true
            docker rm login-service || true
            docker stop register-service || true
            docker rm register-service || true

            docker pull chamorrito/login-service
            docker pull chamorrito/register-service

            docker run -d --name login-service -p 8001:8001 --restart unless-stopped chamorrito/login-service
            docker run -d --name register-service -p 8002:8002 --restart unless-stopped chamorrito/register-service

  deploy-products:
    name: Deploy Products Services
    runs-on: ubuntu-latest
    needs: deploy-auth

    steps:
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEYP }}

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Products images
        run: |
          docker build -t chamorrito/review ./BackEnd/Products-Domain/Reviews
          docker build -t chamorrito/get_review ./BackEnd/Products-Domain/Get_review
          docker build -t chamorrito/cart ./BackEnd/Products-Domain/Cart

      - name: Push Products images
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push chamorrito/review
          docker push chamorrito/get_review
          docker push chamorrito/cart

      - name: Deploy Products services to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 3.93.94.180
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEYP }}
          script: |
            docker stop review || true
            docker rm review || true
            docker stop get_review || true
            docker rm get_review || true
            docker stop cart || true
            docker rm cart || true

            docker pull chamorrito/review
            docker pull chamorrito/get_review
            docker pull chamorrito/cart

            docker run -d --name review -p 5000:5000 --restart unless-stopped chamorrito/review
            docker run -d --name get_review -p 5001:5001 --restart unless-stopped chamorrito/get_review
            docker run -d --name cart -p 5002:5002 --restart unless-stopped chamorrito/cart

  deploy-user:
    name: Deploy User Services
    runs-on: ubuntu-latest
    needs: deploy-products

    steps:
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEYP }}

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build User images
        run: |
          docker build -t chamorrito/change-password ./BackEnd/User-Domain/change-password
          docker build -t chamorrito/delete-account ./BackEnd/User-Domain/delete-user
          docker build -t chamorrito/phrases ./BackEnd/User-Domain/biblio_store_service

      - name: Push User images
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push chamorrito/change-password
          docker push chamorrito/delete-account
          docker push chamorrito/phrases

      - name: Deploy User services to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 54.173.11.82
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEYP }}
          script: |
            docker stop change-password || true
            docker rm change-password || true
            docker stop delete-account || true
            docker rm delete-account || true
            docker stop phrases || true
            docker rm phrases || true

            docker pull chamorrito/change-password
            docker pull chamorrito/delete-account
            docker pull chamorrito/phrases

            docker run -d --name change-password -p 8005:8005 --restart unless-stopped chamorrito/change-password
            docker run -d --name delete-account -p 8004:8004 --restart unless-stopped chamorrito/delete-account
            docker run -d --name phrases -p 5000:5000 --restart unless-stopped chamorrito/phrases
